version: 2

project_name: ingredient-genie

builds:
  - id: frontend
    dir: ./src/frontend
    main: ./cmd/web
    binary: ingredient-genie-frontend
    ldflags: -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

  - id: backend
    dir: ./src/backend
    main: ./cmd/api
    binary: ingredient-genie-backend
    ldflags: -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: frontend
    ids:
      - frontend
    name_template: "ingredient-genie-frontend_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

  - id: backend
    ids:
      - backend
    name_template: "ingredient-genie-backend_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: checksums.txt

changelog:
  sort: asc